<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Umbrella.Core\Umbrella.Core.csproj" />
    <ProjectReference Include="..\FantaTournament.Domain\FantaTournament.Domain.csproj" />
    <ProjectReference Include="..\FantaTournament.Application\FantaTournament.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
